#!/usr/bin/env python3
"""Generate optional capacity notes for the overprovisioning demo."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path


def parse_cpu(value: str) -> int:
    if value.endswith("m"):
        return int(value[:-1])
    return int(float(value) * 1000)


def parse_mem_mi(value: str) -> int:
    match = re.fullmatch(r"([0-9.]+)([KMGTE]i?)?", value)
    if not match:
        raise ValueError(value)
    amount = float(match.group(1))
    suffix = match.group(2) or ""
    factors = {
        "Ki": 1 / 1024,
        "Mi": 1,
        "Gi": 1024,
        "Ti": 1024 * 1024,
        "K": 1000 / 1024 / 1024,
        "M": 1000 / 1024,
        "G": 1000,
        "T": 1000 * 1000,
        "": 1 / 1024 / 1024,
    }
    return int(amount * factors[suffix])


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="helm/generated-values.yaml")
    args = parser.parse_args()

    node_json = subprocess.check_output(["kubectl", "get", "nodes", "-o", "json"], text=True)
    nodes = json.loads(node_json)["items"]
    if not nodes:
        raise SystemExit("No Kubernetes nodes found.")

    node = nodes[0]
    name = node["metadata"]["name"]
    alloc = node["status"]["allocatable"]
    cpu_m = parse_cpu(alloc["cpu"])
    mem_mi = parse_mem_mi(alloc["memory"])
    suggested_cpu_m = max(100, cpu_m * 55 // 100)
    suggested_mem_mi = max(256, mem_mi * 55 // 100)

    content = f"""# Generated by scripts/generate-capacity-values.py.
# Informational only; the JupyterHub chart ignores this file unless you wire it in.
demoCapacity:
  nodeName: {name}
  allocatableCpuMilli: {cpu_m}
  allocatableMemoryMi: {mem_mi}
  suggestedIdleLargeRequest:
    cpu: {suggested_cpu_m}m
    memory: {suggested_mem_mi}Mi
"""
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()

